### ISSUE TITLE
Price should be a number rather than a dropdown

### ISSUE THREAD

**Issue by scottrepreneur** [MetaFactoryAI/mf-app#213]
Price should be an integer and we can add another field for `price_currency`. This will be many-to-one, defaulting to USD.

- use the current field as price_currency?

**Comment by scottrepreneur** [comment]
Ok so we want to minimize impact on data. The ending columns/tables look like
```
products {
  ...
  price - integer // consistent with current `amount` on `price_currencies`
  price_currency - enum @ `price_currencies`  // (USD, ETH)
}

price_currencies {
  currency
}
```

The proposed steps would be
1. Rename `price` to `price_id`, rename `price_currencies` to `price_rel`
2. Create new `price_currencies` as an enum table effectively. Initial values would be USD, ETH, EUR.
3. Add `price_currency` field to `products` that uses this enum as a dropdown
4. Set `price` to integer, `amount` is a decimal in the current `price_currencies`
5. Run migration for records with `price_rel` to update `price` & `price_currency`
6. Remove `price_id` & `price_rel`

Does this break anything while the migrations run? We could alternatively export the current `price_currencies`, do a clean drop of those fields, import with a one-off script?

Can you check my thinking here @META-DREAMER ?

**Comment by META-DREAMER** [comment]
Yea this direction makes sense. In terms of performing the migration, it's best if we don't create new fields/tables that have the same name as the old tables, otherwise when applying snapshot it can get confused.

here's how I would do it:

1. Add a new column to products `sale_price` as a Decimal with 10 precision and 2 scale. ![image](https://user-images.githubusercontent.com/7143583/185199675-479716a3-7ac7-447e-a206-1bf6ebd50614.jpeg)

2. Add a new table `currencies` with a dropdown field to select ETH/USD etc

3. Add a new column to products `sale_currency` as a many to one relation to `currencies`

4. Migrate data for each product from related `price_currencies` table to the new `sale_price` and `sale_currency` columns

5. Hide the price field in products from the UI (don't delete it or remove the price_currencies table)

This makes the migration non destructive / additive only, which is the key to not ending up in a bad state and making it easy for CD. Once this change is rolled out and deployed, we can then make another migration / PR to remove those tables / columns.

For migrating the data, would be great to try out the custom migrations and see if that lets us deploy to prod directly and have it make the migration automatically without having to manually run scripts against prod instance
