### ISSUE TITLE
Bug with unable to download files win10/brave

### ISSUE THREAD

**Issue by madjin** [MetaFactoryAI/mf-app#214]
![Image](https://user-images.githubusercontent.com/32600939/184510692-2cd76c1d-385b-4233-af89-714b13560395.png)

none of the download buttons seem to work

**Comment by scottrepreneur** [comment]
Doesn't appear to be specific to windows in the Edit screen. It looks like there's a workaround at least.

It is working to download them from the Product Detail instead of in their respective Edit pane. Lmk if this doesn't work for you @madjin.

<img width="916" alt="Screen Shot 2022-08-16 at 16 26 06" src="https://user-images.githubusercontent.com/1778380/184988155-939681ef-c794-414e-b903-3fa5f77a4782.png">
